APITaskManagement.Web/Models/ReportViewModel.cs
using APITaskManagement.Logic.Management;
using APITaskManagement.Logic.Schedulers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace APITaskManagement.Web.Models
{
    public class ReportViewModel
    {
        public IEnumerable<Log> Logs { get; set; }
        public int NumberOfInfoMessages { get { return Logs.Count(log => log.PriorityName == "INFO"); } }
        public int NumberOfWarningMessages { get { return Logs.Count(log => log.PriorityName == "WARN"); } }
        public int NumberOfErrorMessages { get { return Logs.Count(log => log.PriorityName == "ERR"); } }
    }
}

APITaskManagement.Web/Controllers/LogController.cs
using APITaskManagement.Logic.Common.Interfaces;
using APITaskManagement.Logic.Management.Repositories;
using APITaskManagement.Logic.Schedulers;
using APITaskManagement.Logic.Schedulers.Repositories;
using System;
using System.Web.Mvc;

namespace APITaskManagement.Web.Controllers
{
    public class LogController : Controller
    {
        private readonly LogRepository _logRepository;

        public LogController()
        {
            _logRepository = new LogRepository();
        }

        // GET: Log
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, string startDate = null, string endDate = null)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TimestampSortParm = String.IsNullOrEmpty(sortOrder) ? "timestamp_desc" : "";
            // ViewBag.PrioritySortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            DateTime start, end;

            if (String.IsNullOrEmpty(startDate) || String.IsNullOrEmpty(endDate))
            {
                var dateNow = DateTime.Now.AddMonths(-1);
                start = DateTime.Now.AddMonths(-1).Date;
                end = DateTime.Now.AddDays(1).Date;
            }
            else
            {
                start = Convert.ToDateTime(startDate);
                end = Convert.ToDateTime(endDate);
            }

            ViewBag.StartDate = start.ToString("yyyy-MM-dd");
            ViewBag.EndDate = end.ToString("yyyy-MM-dd");

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var logs = _logRepository.List(sortOrder, searchString, pageSize, pageNumber, start, end);

            return View(logs);
        }

        // GET: Log/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
    }
}

APITaskManagement.Web/Controllers/ReportController.cs
using APITaskManagement.Logic.Common.Interfaces;
using APITaskManagement.Logic.Management.Repositories;
using APITaskManagement.Logic.Schedulers;
using APITaskManagement.Logic.Schedulers.Repositories;
using APITaskManagement.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APITaskManagement.Web.Controllers
{
    public class ReportController : Controller
    {
        private readonly TaskRepository _taskRepository;
        private readonly LogRepository _logRepository;

        public ReportController()
        {
            _taskRepository = new TaskRepository();
            _logRepository = new LogRepository();
        }

        // GET: Report
        public ActionResult Index(string startDate = null, string endDate = null)
        {
            DateTime start, end;

            if (String.IsNullOrEmpty(startDate) || String.IsNullOrEmpty(endDate))
            {
                var dateNow = DateTime.Now;
                start = dateNow.Date;
                end = start.AddDays(1);
            } 
            else
            {
                start = Convert.ToDateTime(startDate);
                end = Convert.ToDateTime(endDate);
            }

            var reportViewModel = new ReportViewModel { Logs = _logRepository.GetByDate(start, end) };

            ViewBag.StartDate = start.ToString("yyyy-MM-dd");
            ViewBag.EndDate = end.ToString("yyyy-MM-dd");

            return View(reportViewModel);
        }
    }
}

APITaskManagement.Web/Views/Report/Index.cshtml
@{
    ViewBag.Title = "Reports";

    var startDate = ViewBag.StartDate;
    var endDate = ViewBag.EndDate;
}

<h2>Reports</h2>

@using (Html.BeginForm("Index", "Report", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal" }))
{

    <div class="form-group">
        <label for="startDate" class="col-md-1">Start Date</label>
        <div class="col-md-3">
            <input type="date" class="form-control" id="startDate" name="startDate" value="@startDate" />
            <span class="field-validation-valid text-danger" data-valmsg-for="startDate" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="form-group">
        <label for="endDate" class="col-md-1">End Date</label>
        <div class="col-md-3">
            <input type="date" class="form-control" id="endDate" name="endDate" value="@endDate" />
            <span class="field-validation-valid text-danger" data-valmsg-for="endDate" data-valmsg-replace="true"></span>
        </div>
    </div>

}

<hr />


<div class="row">
    <div class="col-md-12">
        Total events: @Model.Logs.Count
    </div>
    <div class="col-md-4">
        <ul class="list-group">
            <li class="list-group-item">
                <span class="badge">@Model.NumberOfInfoMessages</span>
                @if (Model.NumberOfInfoMessages > 0)
                {
                    @Html.ActionLink("Information", "Index", "Log", new { startDate = startDate, endDate = endDate, errorType = "INFO" }, new { @style = "color: green; text-decoration: underline;" });
                }
                else
                {
                    <span style="color: green;">Information: </span>
                }
            </li>
            <li class="list-group-item">
                <span class="badge">@Model.NumberOfWarningMessages</span>
                @if (Model.NumberOfWarningMessages > 0)
                {
                    @Html.ActionLink("Warning", "Index", "Log", new { startDate = startDate, endDate = endDate, errorType = "WARN" }, new { @style = "color: darkorange; text-decoration: underline;" });
                }
                else
                {
                    <span style="color: darkorange;">Warning</span>
                }
            </li>
            <li class="list-group-item">
                <span class="badge">@Model.NumberOfErrorMessages</span>
                @if (Model.NumberOfErrorMessages > 0)
                {
                    @Html.ActionLink("Error", "Index", "Log", new { startDate = startDate, endDate = endDate, errorType = "ERR" }, new { @style = "color: red; text-decoration: underline;" });
                }
                else
                {
                    <span style="color: red;">Error</span>
                }
            </li>
        </ul>
    </div>
</div>

@section scripts  {
    <script type="text/javascript">
        function dateRangeValid() {
            var startDate = new Date($("#startDate").val());
            var endDate = new Date($("#endDate").val());

            if (startDate >= endDate) {
                return false;
            } else {
                return true;
            }
        }


        $(function () {

            var currentStartDate = $("#startDate").val();
            var currentEndDate = $("#endDate").val();

            $("#startDate").change(function (e) {
                if (dateRangeValid()) {
                    $("form").submit();
                } else {
                    $("#startDate").val(currentStartDate);
                    $("form").find("[data-valmsg-for='startDate']").text("Start Date should be less than End Date");
                }
            });

            $("#endDate").change(function (e) {
                if (dateRangeValid()) {
                    $("form").submit();
                } else {
                    $("#endDate").val(currentEndDate);
                    $("form").find("[data-valmsg-for='endDate']").text("End Date should be greater than Start Date");
                }
            });

        });
    </script>
}